name: Fetch News Articles
on:
  schedule:
    - cron: '0 */3 * * *' # Toutes les 3 heures
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch new articles
        run: |
          node -e "
          const axios = require('axios');
          const fs = require('fs');

          const API_KEY = 'fce4d310a188453eaa6c3118531b7226';
          const QUERY = 'Algérie';
          const LANGUAGE = 'fr';
          const PAGE_SIZE = 20;

          // Lire les articles existants
          let existingArticles = [];
          try {
            existingArticles = JSON.parse(fs.readFileSync('articles.json', 'utf8'));
          } catch (error) {
            console.log('Aucun fichier articles.json trouvé, création d\'un nouveau fichier.');
          }

          // Récupérer la date du dernier article
          const lastArticleDate = existingArticles.length > 0
            ? new Date(existingArticles[0].publishedAt)
            : new Date(0); // Si aucun article, utiliser une date très ancienne

          // Récupérer les nouveaux articles depuis NewsAPI
          axios.get(\`https://newsapi.org/v2/everything?q=\${QUERY}&language=\${LANGUAGE}&pageSize=\${PAGE_SIZE}&sortBy=publishedAt&apiKey=\${API_KEY}\`)
            .then(response => {
              if (response.data.status === 'ok') {
                const newArticles = response.data.articles.filter(article => {
                  const articleDate = new Date(article.publishedAt);
                  return articleDate > lastArticleDate; // Filtrer les articles plus récents
                });

                if (newArticles.length > 0) {
                  // Fusionner les nouveaux articles avec les anciens
                  const updatedArticles = [...newArticles, ...existingArticles];
                  fs.writeFileSync('articles.json', JSON.stringify(updatedArticles));
                  console.log(\`${newArticles.length} nouveaux articles ajoutés.\`);
                } else {
                  console.log('Aucun nouvel article trouvé.');
                }
              } else {
                console.error('Erreur NewsAPI :', response.data);
              }
            })
            .catch(error => {
              console.error('Erreur lors de la récupération des articles :', error);
            });
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add articles.json
          git commit -m 'Mise à jour des articles'
          git push
